# Generated by Django 2.0.2 on 2018-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_remove_pin_cumulative_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='block_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_type',
            field=models.PositiveIntegerField(choices=[(1, 'Recursive'), (2, 'Indirect'), (3, 'MFS root')], default=1),
            preserve_default=False,
        ),
    ]
