# Generated by Django 2.0.2 on 2018-03-22 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0004_auto_20180322_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_type',
            field=models.PositiveIntegerField(choices=[(0, 'Direct'), (1, 'Recursive'), (2, 'Indirect'), (3, 'MFS root')]),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL),
        ),
    ]
