# Generated by Django 2.0.2 on 2018-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='multihash',
            field=models.CharField(db_index=True, help_text='The multihash of the IPFS object to pin', max_length=64),
        ),
    ]
